### ISSUE TITLE
only install pandoc if it is not already present

### ISSUE THREAD

**Issue by dtenenba** [road2stat/liftr#12]
The Bioconductor Docker images are based on rocker/rstudio which means they already have pandoc installed. liftr tries to install pandoc on the container and this fails. The dockerfile should only attempt to install pandoc if it is not already installed. Thanks.

**Comment by nanxstats** [comment]
@dtenenba - confirmed. Thanks Dan. This will be soon fixed in the development version on GitHub.

**Comment by nanxstats** [comment]
@dtenenba - hi Dan, this issue has been fixed in the current version (v0.2) on GitHub. Try `devtools::install_github("road2stat/liftr")` to install it. We've also submitted v0.2 to CRAN, waiting to be reviewed. (update: v0.2 is on CRAN now.)

In v0.2, if `rocker/rstudio` or one  of the Bioconductor images is specified, Pandoc will not be installed. We also provided a new option `pandoc` in the liftr metadata to allow users to control whether to install Pandoc or not.
