### ISSUE TITLE
seeking a solution for both Python and R user..

### ISSUE THREAD

**Issue by harryprince** [road2stat/liftr#21]
I am both using Python and R, can I see any solution to describe the python dependancies like R? or how I can contribute for that?

**Comment by harryprince** [comment]
And I fail to find how to change the default CRAN repo mirror. I just wanna set the mirror as https://mirrors.tuna.tsinghua.edu.cn/CRAN/

probably pass as an environment variable with -e parameter in docker is a good solution.

**Comment by nanxstats** [comment]
Currently, we do not have plans for supporting package management systems for languages other than R, but that could be an idea to consider.

So, please declare them as system dependencies if they could be installed via `apt-get`. Another possibility is installing them on-the-fly in R Markdown code chunks since [knitr supports that](http://yihui.name/knitr/demo/engines/).

**Comment by nanxstats** [comment]
@harryprince - now this should be fixed by https://github.com/road2stat/liftr/commit/e332619fdcdd11a7a00c0281cbc9337595e67afc.

The new `include` field allows users to include any custom Dockerfile snippets.
